### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by marki123** [Dasrg/steam-reportbot#1]
Chunk 2 finished: Successfully reported 0 times and 2 failed requests
Waiting 5000 ms for the next chunk
[eathadderc4nguyen3947] Unable to auth (Error: Error: CAPTCHA
    at SteamCommunity.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-reportbot-master\node_modules\steamcommunity\index.js:155:13)
    at Request._callback (C:\Users\markg\Desktop\cmdb\steam-reportbot-master\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\markg\Desktop\cmdb\steam-reportbot-master\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-reportbot-master\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-reportbot-master\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12) {
  captchaurl: 'https://steamcommunity.com/login/rendercaptcha/?gid=3763278844859720225'
})
[edkingcrabi723pucci] Unable to auth (Error: Error: CAPTCHA
    at SteamCommunity.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-reportbot-master\node_modules\steamcommunity\index.js:155:13)
    at Request._callback (C:\Users\markg\Desktop\cmdb\steam-reportbot-master\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\markg\Desktop\cmdb\steam-reportbot-master\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-reportbot-master\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-reportbot-master\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12) {
  captchaurl: 'https://steamcommunity.com/login/rendercaptcha/?gid=3763278844859720229'
})
Chunk 3 finished: Successfully reported 0 times and 2 failed requests
Successfully reported 0 times and 6 failed requests.

**Comment by virtualtear** [comment]
Is because an alt wasn't working.. normal error tho

**Comment by amx22** [comment]
I think the program is not working? @darby-dev 
I'm getting the same error 'captcha
